apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      -  image: nginx
         name: nginc-ctr
---         
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-clusterip-svc
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - name: nginx-port
      protocol: TCP
      port: 32767
      targetPort: 80
      nodePort: 30000
